FROM python:3.12

RUN apt-get update && apt-get install -y \
    build-essential \
    vim git curl \
    && rm -rf /var/lib/apt/lists/*

# Optional: install Jupyter, ipython for debugging
RUN pip install ipython jupyter