[tool.ruff]
line-length = 88
target-version = "py312"
exclude = ["venv", ".venv", "__pycache__"]
fix = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.ruff.lint]
select = ["E", "F", "I", "B"]
ignore = ["E501"]

[tool.isort]
profile = "black"
line-length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true